import { imageConfig } from './config'

/**
 * 原 JSON 原文筛选版。保留项的 prompt 正文未被改写。
 * 筛选规则：删除原全局序号 1–101 与 108；103 标题改为“根据cos角色修图”；删除重绘幅度、空场景变量项，以及没有明确约束语句的条目。
 */
export type PromptLibraryCategoryId = 'all' | 'base' | 'portrait' | 'outfit' | 'material' | 'lighting' | 'scene' | 'effect' | 'creative' | 'semi-composite-prefab'
export type PromptLibraryItemCategoryId = Exclude<PromptLibraryCategoryId, 'all'>
export type PromptLibraryCategory = { id: PromptLibraryCategoryId; label: string }
export type PromptLibrarySubcategory = { id: string; category: PromptLibraryItemCategoryId; label: string }
export type PromptLibraryItem = { id: string; category: PromptLibraryItemCategoryId; subCategory: string; title: string; image: string; tags: string[]; prompt: string; params: string }
export const promptLibraryCategories: PromptLibraryCategory[] = [
  { id: 'all', label: '全部' },
  { id: 'base', label: '基础与控制' },
  { id: 'portrait', label: '人物' },
  { id: 'outfit', label: '服装与配饰' },
  { id: 'material', label: '材质与道具' },
  { id: 'lighting', label: '光影与摄影' },
  { id: 'scene', label: '场景' },
  { id: 'effect', label: '特效' },
  { id: 'creative', label: '创意' },
  { id: 'semi-composite-prefab', label: '半合成场景预制菜' },
]
export const promptLibrarySubcategories: PromptLibrarySubcategory[] = [
  { id: "sub-1", category: "base", label: "基础-身份 / 工作流" },
  { id: "sub-2", category: "base", label: "基础-增强 / 超清 / 放大" },
  { id: "sub-3", category: "base", label: "基础-负面提示 / 约束" },
  { id: "sub-5", category: "base", label: "自用" },
  { id: "sub-6", category: "base", label: "控制-锁定 / 组合 / 替换流程" },
  { id: "sub-7", category: "portrait", label: "人物-头部 / 面部综合" },
  { id: "sub-8", category: "portrait", label: "人物-脸型 / 轮廓 / 修容 / 气质" },
  { id: "sub-9", category: "portrait", label: "️ 人物-眼睛 / 眉眼 / 眼神" },
  { id: "sub-10", category: "portrait", label: "人物-鼻子 / 嘴唇 / 牙齿 / 泪痕" },
  { id: "sub-11", category: "portrait", label: "人物-头发 / 刘海 / 发际线 / 飘发" },
  { id: "sub-12", category: "portrait", label: "人物-皮肤 / 毛孔 / 磨皮 / 肤色" },
  { id: "sub-13", category: "portrait", label: "人物-颈部 / 肩颈 / 锁骨" },
  { id: "sub-14", category: "portrait", label: "人物-胸部 / 腰腹 / 马甲线" },
  { id: "sub-15", category: "portrait", label: "人物-手臂 / 肩膀" },
  { id: "sub-16", category: "portrait", label: "人物-手部 / 手指 / 美甲 / 手套" },
  { id: "sub-17", category: "portrait", label: "人物-腿部 / 膝盖 / 腿型" },
  { id: "sub-18", category: "portrait", label: "人物-脚部 / 玉足" },
  { id: "sub-19", category: "portrait", label: "人物-全身 / 身材 / 姿态 / 性转" },
  { id: "sub-20", category: "outfit", label: "服装-整体 / 版型 / 合身 / 褶皱" },
  { id: "sub-21", category: "outfit", label: "服装-丝袜 / 白丝 / 黑丝 / 网袜 / 打底" },
  { id: "sub-22", category: "outfit", label: "配饰-饰品 / 头饰 / 小配件" },
  { id: "sub-23", category: "material", label: "材质-布料 / 针织 / 棉麻 / 丝绸" },
  { id: "sub-24", category: "material", label: "材质-皮革 / 尼龙 / 乳胶 / 装甲" },
  { id: "sub-25", category: "material", label: "️ 材质-金属 / 木质 / 道具 / 通用物体" },
  { id: "sub-26", category: "material", label: "武器-枪械 / 刃口 / 战术装备" },
  { id: "sub-27", category: "lighting", label: "光影-布光 / 投影 / 反射 / AO" },
  { id: "sub-28", category: "lighting", label: "氛围-调色 / 风格化 / 色温" },
  { id: "sub-29", category: "lighting", label: "摄影-构图 / 镜头 / 景深 / 画质" },
  { id: "sub-30", category: "base", label: "去杂物-擦除 / 修补 / 去水印 / 白棚" },
  { id: "sub-31", category: "scene", label: "️ 背景-抠图 / 换背景 / 场景替换" },
  { id: "sub-33", category: "effect", label: "特效-光效 / 粒子 / 元素 / 魔法" },
  { id: "sub-34", category: "effect", label: "特效-流体 / 湿身 / 雨水 / 粘液" },
  { id: "sub-35", category: "effect", label: "特效-战损 / 脏污 / 伤疤 / 老化" },
  { id: "sub-36", category: "creative", label: "创意-植入 / 重构 / 动作设计 / 建模 / Fufu" },
  { id: "semi-composite-prefab-prompts", category: "semi-composite-prefab", label: "半合成场景预制菜提示词" },
  { id: "personal-common", category: "base", label: "个人常用" },
]
const BLACK = imageConfig.placeholders.black
const WHITE = imageConfig.placeholders.white

/** Keep these ten slots at the bottom of the library for future personal uploads. */
const personalCommonPlaceholders: PromptLibraryItem[] = Array.from({ length: 10 }, (_, index) => ({
  id: `personal-common-${index + 1}`,
  category: 'base',
  subCategory: 'personal-common',
  title: `待补充提示词 ${String(index + 1).padStart(2, '0')}`,
  image: BLACK,
  tags: ['个人常用', '待补充'],
  prompt: '', params: '待填写参数',
}))

/** Keep these fifty slots reserved for the semi-composite scene prefab prompt library. */
const semiCompositePrefabPlaceholders: PromptLibraryItem[] = Array.from({ length: 50 }, (_, index) => ({
  id: `semi-composite-prefab-${index + 1}`,
  category: 'semi-composite-prefab',
  subCategory: 'semi-composite-prefab-prompts',
  title: `半合成场景预制菜提示词 ${String(index + 1).padStart(2, '0')}`,
  image: BLACK,
  tags: ['半合成场景预制菜', '待补充'],
  prompt: '', params: '',
}))

export const promptLibraryItems: PromptLibraryItem[] = ([
  { id: "source-103", category: "base", subCategory: "sub-1", title: "根据cos角色修图", image: WHITE, tags: ["基础-身份 / 工作流","base"], prompt: '', params: "原始使用 9 次" },
  { id: "source-105", category: "base", subCategory: "sub-1", title: "cos修图许愿机", image: BLACK, tags: ["基础-身份 / 工作流","base"], prompt: '', params: "原始使用 1 次" },
  { id: "source-106", category: "base", subCategory: "sub-1", title: "许愿机", image: WHITE, tags: ["基础-身份 / 工作流","base"], prompt: '', params: "原始使用 1 次" },
  { id: "source-107", category: "base", subCategory: "sub-1", title: "COS角色指定-填入作品和名字", image: BLACK, tags: ["基础-身份 / 工作流","base"], prompt: '', params: "原始使用 1 次" },
  { id: "source-112", category: "base", subCategory: "sub-2", title: "高清放大", image: WHITE, tags: ["基础-增强 / 超清 / 放大","base"], prompt: '', params: "原始使用 36 次" },
  { id: "source-117", category: "base", subCategory: "sub-2", title: "降噪保细节", image: BLACK, tags: ["基础-增强 / 超清 / 放大","base"], prompt: '', params: "原始使用 5 次" },
  { id: "source-121", category: "base", subCategory: "sub-2", title: "超清修复", image: WHITE, tags: ["基础-增强 / 超清 / 放大","base"], prompt: '', params: "原始使用 0 次" },
  { id: "source-123", category: "base", subCategory: "sub-3", title: "通用", image: BLACK, tags: ["基础-负面提示 / 约束","base","收藏"], prompt: '', params: "原始使用 12 次 / 收藏" },
  { id: "source-126", category: "base", subCategory: "sub-3", title: "构图锁定（全身/半身/特写）", image: WHITE, tags: ["基础-负面提示 / 约束","base"], prompt: '', params: "原始使用 0 次" },
  { id: "source-127", category: "base", subCategory: "sub-3", title: "颜色保持", image: BLACK, tags: ["基础-负面提示 / 约束","base"], prompt: '', params: "原始使用 0 次" },
  { id: "source-130", category: "base", subCategory: "sub-5", title: "白大褂", image: WHITE, tags: ["自用","base"], prompt: '', params: "原始使用 4 次" },
  { id: "source-131", category: "base", subCategory: "sub-5", title: "真实照片", image: BLACK, tags: ["自用","base","收藏"], prompt: '', params: "原始使用 15 次 / 收藏" },
  { id: "source-133", category: "base", subCategory: "sub-5", title: "工业产品", image: WHITE, tags: ["自用","base"], prompt: '', params: "原始使用 0 次" },
  { id: "source-134", category: "base", subCategory: "sub-5", title: "角色展示", image: BLACK, tags: ["自用","base"], prompt: '', params: "原始使用 0 次" },
  { id: "source-135", category: "base", subCategory: "sub-5", title: "脱衣服穿防弹衣", image: WHITE, tags: ["自用","base"], prompt: '', params: "原始使用 2 次" },
  { id: "source-136", category: "base", subCategory: "sub-5", title: "放下右图的手", image: BLACK, tags: ["自用","base"], prompt: '', params: "原始使用 0 次" },
  { id: "source-138", category: "base", subCategory: "sub-5", title: "加虚化（F1.2）", image: WHITE, tags: ["自用","base"], prompt: '', params: "原始使用 8 次" },
  { id: "source-139", category: "base", subCategory: "sub-5", title: "放大", image: BLACK, tags: ["自用","base"], prompt: '', params: "原始使用 19 次" },
  { id: "source-143", category: "base", subCategory: "sub-5", title: "女队长", image: WHITE, tags: ["自用","base"], prompt: '', params: "原始使用 1 次" },
  { id: "source-144", category: "base", subCategory: "sub-5", title: "三联弹挂", image: BLACK, tags: ["自用","base"], prompt: '', params: "原始使用 2 次" },
  { id: "source-145", category: "base", subCategory: "sub-5", title: "战术裤子", image: WHITE, tags: ["自用","base"], prompt: '', params: "原始使用 0 次" },
  { id: "source-146", category: "base", subCategory: "sub-5", title: "战术衬衫", image: BLACK, tags: ["自用","base"], prompt: '', params: "原始使用 1 次" },
  { id: "source-147", category: "base", subCategory: "sub-5", title: "腿挂", image: WHITE, tags: ["自用","base"], prompt: '', params: "原始使用 0 次" },
  { id: "source-148", category: "base", subCategory: "sub-5", title: "头盔", image: BLACK, tags: ["自用","base"], prompt: '', params: "原始使用 0 次" },
  { id: "source-150", category: "base", subCategory: "sub-6", title: "固定人物", image: WHITE, tags: ["控制-锁定 / 组合 / 替换流程","base"], prompt: '', params: "原始使用 1 次" },
  { id: "source-152", category: "base", subCategory: "sub-6", title: "锁人+换氛围", image: BLACK, tags: ["控制-锁定 / 组合 / 替换流程","base"], prompt: '', params: "原始使用 3 次" },
  { id: "source-153", category: "base", subCategory: "sub-6", title: "只改动作", image: WHITE, tags: ["控制-锁定 / 组合 / 替换流程","base"], prompt: '', params: "原始使用 0 次" },
  { id: "source-154", category: "base", subCategory: "sub-6", title: "只改材质", image: BLACK, tags: ["控制-锁定 / 组合 / 替换流程","base"], prompt: '', params: "原始使用 3 次" },
  { id: "source-155", category: "base", subCategory: "sub-6", title: "替换道具", image: WHITE, tags: ["控制-锁定 / 组合 / 替换流程","base"], prompt: '', params: "原始使用 0 次" },
  { id: "source-156", category: "base", subCategory: "sub-6", title: "修透视", image: BLACK, tags: ["控制-锁定 / 组合 / 替换流程","base"], prompt: '', params: "原始使用 17 次" },
  { id: "source-158", category: "base", subCategory: "sub-6", title: "替换图2动作（推荐）", image: WHITE, tags: ["控制-锁定 / 组合 / 替换流程","base"], prompt: '', params: "原始使用 3 次" },
  { id: "source-160", category: "base", subCategory: "sub-6", title: "锁定打光", image: BLACK, tags: ["控制-锁定 / 组合 / 替换流程","base"], prompt: '', params: "原始使用 4 次" },
  { id: "source-161", category: "base", subCategory: "sub-6", title: "锁定动作", image: WHITE, tags: ["控制-锁定 / 组合 / 替换流程","base"], prompt: '', params: "原始使用 1 次" },
  { id: "source-162", category: "base", subCategory: "sub-6", title: "锁定氛围", image: BLACK, tags: ["控制-锁定 / 组合 / 替换流程","base"], prompt: '', params: "原始使用 1 次" },
  { id: "source-163", category: "base", subCategory: "sub-6", title: "换动作", image: WHITE, tags: ["控制-锁定 / 组合 / 替换流程","base"], prompt: '', params: "原始使用 3 次" },
  { id: "source-164", category: "base", subCategory: "sub-6", title: "人物保持，配合道具、特效、背景合成提示词使用", image: BLACK, tags: ["控制-锁定 / 组合 / 替换流程","base"], prompt: '', params: "原始使用 0 次" },
  { id: "source-165", category: "base", subCategory: "sub-6", title: "咒语前缀", image: WHITE, tags: ["控制-锁定 / 组合 / 替换流程","base"], prompt: '', params: "原始使用 0 次" },
  { id: "source-168", category: "portrait", subCategory: "sub-7", title: "替换脸", image: BLACK, tags: ["人物-头部 / 面部综合","portrait"], prompt: '', params: "原始使用 6 次" },
  { id: "source-170", category: "portrait", subCategory: "sub-7", title: "复制脸", image: WHITE, tags: ["人物-头部 / 面部综合","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-171", category: "portrait", subCategory: "sub-7", title: "换脸", image: BLACK, tags: ["人物-头部 / 面部综合","portrait"], prompt: '', params: "原始使用 7 次" },
  { id: "source-172", category: "portrait", subCategory: "sub-7", title: "面部精修1111", image: WHITE, tags: ["人物-头部 / 面部综合","portrait"], prompt: '', params: "原始使用 1 次" },
  { id: "source-173", category: "portrait", subCategory: "sub-7", title: "复制脸修容", image: BLACK, tags: ["人物-头部 / 面部综合","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-174", category: "portrait", subCategory: "sub-7", title: "上半身一键", image: WHITE, tags: ["人物-头部 / 面部综合","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-175", category: "portrait", subCategory: "sub-8", title: "CG感修容", image: BLACK, tags: ["人物-脸型 / 轮廓 / 修容 / 气质","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-176", category: "portrait", subCategory: "sub-8", title: "厚涂感修容", image: WHITE, tags: ["人物-脸型 / 轮廓 / 修容 / 气质","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-177", category: "portrait", subCategory: "sub-8", title: "自然感修容", image: BLACK, tags: ["人物-脸型 / 轮廓 / 修容 / 气质","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-179", category: "portrait", subCategory: "sub-8", title: "换脸型/轮廓", image: WHITE, tags: ["人物-脸型 / 轮廓 / 修容 / 气质","portrait"], prompt: '', params: "原始使用 2 次" },
  { id: "source-180", category: "portrait", subCategory: "sub-8", title: "下颌线优化", image: BLACK, tags: ["人物-脸型 / 轮廓 / 修容 / 气质","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-181", category: "portrait", subCategory: "sub-8", title: "御姐脸型(可调参数)", image: WHITE, tags: ["人物-脸型 / 轮廓 / 修容 / 气质","portrait"], prompt: '', params: "原始使用 1 次" },
  { id: "source-182", category: "portrait", subCategory: "sub-8", title: "萝莉脸型(可调参数)", image: BLACK, tags: ["人物-脸型 / 轮廓 / 修容 / 气质","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-183", category: "portrait", subCategory: "sub-8", title: "乙女向美男脸(可调参数)", image: WHITE, tags: ["人物-脸型 / 轮廓 / 修容 / 气质","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-184", category: "portrait", subCategory: "sub-8", title: "成熟男性脸(可调参数)", image: BLACK, tags: ["人物-脸型 / 轮廓 / 修容 / 气质","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-185", category: "portrait", subCategory: "sub-8", title: "少年感中性脸(可调参数)", image: WHITE, tags: ["人物-脸型 / 轮廓 / 修容 / 气质","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-186", category: "portrait", subCategory: "sub-8", title: "邪魅反派脸(可调参数)", image: BLACK, tags: ["人物-脸型 / 轮廓 / 修容 / 气质","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-187", category: "portrait", subCategory: "sub-8", title: "清冷仙侠脸(可调参数)", image: WHITE, tags: ["人物-脸型 / 轮廓 / 修容 / 气质","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-188", category: "portrait", subCategory: "sub-8", title: "甜美偶像脸(可调参数)", image: BLACK, tags: ["人物-脸型 / 轮廓 / 修容 / 气质","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-192", category: "portrait", subCategory: "sub-9", title: "换眼睛", image: WHITE, tags: ["️ 人物-眼睛 / 眉眼 / 眼神","portrait"], prompt: '', params: "原始使用 1 次" },
  { id: "source-193", category: "portrait", subCategory: "sub-9", title: "眼球质感增强", image: BLACK, tags: ["️ 人物-眼睛 / 眉眼 / 眼神","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-194", category: "portrait", subCategory: "sub-9", title: "瞳孔提亮", image: WHITE, tags: ["️ 人物-眼睛 / 眉眼 / 眼神","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-195", category: "portrait", subCategory: "sub-9", title: "精致眼妆", image: BLACK, tags: ["️ 人物-眼睛 / 眉眼 / 眼神","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-196", category: "portrait", subCategory: "sub-9", title: "精致眉形", image: WHITE, tags: ["️ 人物-眼睛 / 眉眼 / 眼神","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-197", category: "portrait", subCategory: "sub-10", title: "修复嘴唇干裂", image: BLACK, tags: ["人物-鼻子 / 嘴唇 / 牙齿 / 泪痕","portrait"], prompt: '', params: "原始使用 1 次" },
  { id: "source-198", category: "portrait", subCategory: "sub-10", title: "牙齿美白自然", image: WHITE, tags: ["人物-鼻子 / 嘴唇 / 牙齿 / 泪痕","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-199", category: "portrait", subCategory: "sub-10", title: "鼻梁高光", image: BLACK, tags: ["人物-鼻子 / 嘴唇 / 牙齿 / 泪痕","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-200", category: "portrait", subCategory: "sub-10", title: "柔化唇纹", image: WHITE, tags: ["人物-鼻子 / 嘴唇 / 牙齿 / 泪痕","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-201", category: "portrait", subCategory: "sub-10", title: "泪痕哭泣效果", image: BLACK, tags: ["人物-鼻子 / 嘴唇 / 牙齿 / 泪痕","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-202", category: "portrait", subCategory: "sub-10", title: "唾液丝效果", image: WHITE, tags: ["人物-鼻子 / 嘴唇 / 牙齿 / 泪痕","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-203", category: "portrait", subCategory: "sub-11", title: "头发（真实发丝、去杂发、轻微飘扬）", image: BLACK, tags: ["人物-头发 / 刘海 / 发际线 / 飘发","portrait"], prompt: '', params: "原始使用 8 次" },
  { id: "source-204", category: "portrait", subCategory: "sub-11", title: "一键飘发", image: WHITE, tags: ["人物-头发 / 刘海 / 发际线 / 飘发","portrait"], prompt: '', params: "原始使用 1 次" },
  { id: "source-209", category: "portrait", subCategory: "sub-11", title: "祛碎发", image: BLACK, tags: ["人物-头发 / 刘海 / 发际线 / 飘发","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-210", category: "portrait", subCategory: "sub-11", title: "头发超写实", image: WHITE, tags: ["人物-头发 / 刘海 / 发际线 / 飘发","portrait","收藏"], prompt: '', params: "原始使用 29 次 / 收藏" },
  { id: "source-211", category: "portrait", subCategory: "sub-11", title: "修复发际线", image: BLACK, tags: ["人物-头发 / 刘海 / 发际线 / 飘发","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-212", category: "portrait", subCategory: "sub-11", title: "头发优化(JSON)", image: WHITE, tags: ["人物-头发 / 刘海 / 发际线 / 飘发","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-213", category: "portrait", subCategory: "sub-11", title: "亮闪闪头发", image: BLACK, tags: ["人物-头发 / 刘海 / 发际线 / 飘发","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-214", category: "portrait", subCategory: "sub-11", title: "动态头发(画笔引导)", image: WHITE, tags: ["人物-头发 / 刘海 / 发际线 / 飘发","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-215", category: "portrait", subCategory: "sub-11", title: "长发飘动风吹", image: BLACK, tags: ["人物-头发 / 刘海 / 发际线 / 飘发","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-216", category: "portrait", subCategory: "sub-11", title: "CG写实毛发", image: WHITE, tags: ["人物-头发 / 刘海 / 发际线 / 飘发","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-217", category: "portrait", subCategory: "sub-11", title: "手绘感毛发", image: BLACK, tags: ["人物-头发 / 刘海 / 发际线 / 飘发","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-218", category: "portrait", subCategory: "sub-11", title: "刘海修整优化", image: WHITE, tags: ["人物-头发 / 刘海 / 发际线 / 飘发","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-219", category: "portrait", subCategory: "sub-11", title: "柔顺头发", image: BLACK, tags: ["人物-头发 / 刘海 / 发际线 / 飘发","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-228", category: "portrait", subCategory: "sub-12", title: "皮肤/质感（影视CG、去油腻）", image: WHITE, tags: ["人物-皮肤 / 毛孔 / 磨皮 / 肤色","portrait","收藏"], prompt: '', params: "原始使用 11 次 / 收藏" },
  { id: "source-229", category: "portrait", subCategory: "sub-12", title: "清晰化/修复（毛孔、眉睫、唇纹、发丝光泽；避免塑料感）", image: BLACK, tags: ["人物-皮肤 / 毛孔 / 磨皮 / 肤色","portrait"], prompt: '', params: "原始使用 2 次" },
  { id: "source-233", category: "portrait", subCategory: "sub-12", title: "光滑皮肤", image: WHITE, tags: ["人物-皮肤 / 毛孔 / 磨皮 / 肤色","portrait"], prompt: '', params: "原始使用 2 次" },
  { id: "source-234", category: "portrait", subCategory: "sub-12", title: "皮肤超写实", image: BLACK, tags: ["人物-皮肤 / 毛孔 / 磨皮 / 肤色","portrait","收藏"], prompt: '', params: "原始使用 40 次 / 收藏" },
  { id: "source-236", category: "portrait", subCategory: "sub-12", title: "修复皮肤油光", image: WHITE, tags: ["人物-皮肤 / 毛孔 / 磨皮 / 肤色","portrait"], prompt: '', params: "原始使用 2 次" },
  { id: "source-237", category: "portrait", subCategory: "sub-12", title: "增加面部桃绒", image: BLACK, tags: ["人物-皮肤 / 毛孔 / 磨皮 / 肤色","portrait"], prompt: '', params: "原始使用 1 次" },
  { id: "source-238", category: "portrait", subCategory: "sub-12", title: "强化T区立体感", image: WHITE, tags: ["人物-皮肤 / 毛孔 / 磨皮 / 肤色","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-239", category: "portrait", subCategory: "sub-12", title: "去黑眼圈/眼袋", image: BLACK, tags: ["人物-皮肤 / 毛孔 / 磨皮 / 肤色","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-240", category: "portrait", subCategory: "sub-12", title: "增加肤色层次", image: WHITE, tags: ["人物-皮肤 / 毛孔 / 磨皮 / 肤色","portrait"], prompt: '', params: "原始使用 2 次" },
  { id: "source-241", category: "portrait", subCategory: "sub-12", title: "皮肤磨皮", image: BLACK, tags: ["人物-皮肤 / 毛孔 / 磨皮 / 肤色","portrait"], prompt: '', params: "原始使用 1 次" },
  { id: "source-242", category: "portrait", subCategory: "sub-12", title: "补妆(JSON)", image: WHITE, tags: ["人物-皮肤 / 毛孔 / 磨皮 / 肤色","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-243", category: "portrait", subCategory: "sub-13", title: "肩颈优化", image: BLACK, tags: ["人物-颈部 / 肩颈 / 锁骨","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-244", category: "portrait", subCategory: "sub-14", title: "G杯", image: WHITE, tags: ["人物-胸部 / 腰腹 / 马甲线","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-246", category: "portrait", subCategory: "sub-14", title: "扩胸", image: BLACK, tags: ["人物-胸部 / 腰腹 / 马甲线","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-248", category: "portrait", subCategory: "sub-14", title: "胸部扩大", image: WHITE, tags: ["人物-胸部 / 腰腹 / 马甲线","portrait"], prompt: '', params: "原始使用 1 次" },
  { id: "source-249", category: "portrait", subCategory: "sub-14", title: "腰部纤细", image: BLACK, tags: ["人物-胸部 / 腰腹 / 马甲线","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-250", category: "portrait", subCategory: "sub-14", title: "腹肌线条", image: WHITE, tags: ["人物-胸部 / 腰腹 / 马甲线","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-252", category: "portrait", subCategory: "sub-15", title: "手臂纤细", image: BLACK, tags: ["人物-手臂 / 肩膀","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-254", category: "portrait", subCategory: "sub-16", title: "手指纤细美化", image: WHITE, tags: ["人物-手部 / 手指 / 美甲 / 手套","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-255", category: "portrait", subCategory: "sub-16", title: "手部皮肤优化", image: BLACK, tags: ["人物-手部 / 手指 / 美甲 / 手套","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-256", category: "portrait", subCategory: "sub-16", title: "美甲优化生成", image: WHITE, tags: ["人物-手部 / 手指 / 美甲 / 手套","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-258", category: "portrait", subCategory: "sub-17", title: "关节美白", image: BLACK, tags: ["人物-腿部 / 膝盖 / 腿型","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-259", category: "portrait", subCategory: "sub-17", title: "修长美腿", image: WHITE, tags: ["人物-腿部 / 膝盖 / 腿型","portrait"], prompt: '', params: "原始使用 1 次" },
  { id: "source-260", category: "portrait", subCategory: "sub-17", title: "腿部中性灰精修", image: BLACK, tags: ["人物-腿部 / 膝盖 / 腿型","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-261", category: "portrait", subCategory: "sub-17", title: "腿部勒肉感", image: WHITE, tags: ["人物-腿部 / 膝盖 / 腿型","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-262", category: "portrait", subCategory: "sub-17", title: "匀肤", image: BLACK, tags: ["人物-腿部 / 膝盖 / 腿型","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-263", category: "portrait", subCategory: "sub-18", title: "光腿神器变玉足", image: WHITE, tags: ["人物-脚部 / 玉足","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-264", category: "portrait", subCategory: "sub-18", title: "脚部清洁美化", image: BLACK, tags: ["人物-脚部 / 玉足","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-265", category: "portrait", subCategory: "sub-18", title: "脚部形态优化", image: WHITE, tags: ["人物-脚部 / 玉足","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-266", category: "portrait", subCategory: "sub-19", title: "液化", image: BLACK, tags: ["人物-全身 / 身材 / 姿态 / 性转","portrait"], prompt: '', params: "原始使用 5 次" },
  { id: "source-268", category: "portrait", subCategory: "sub-19", title: "一键吹风+液化", image: WHITE, tags: ["人物-全身 / 身材 / 姿态 / 性转","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-269", category: "portrait", subCategory: "sub-19", title: "勒肉 抹油", image: BLACK, tags: ["人物-全身 / 身材 / 姿态 / 性转","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-270", category: "portrait", subCategory: "sub-19", title: "优化身材", image: WHITE, tags: ["人物-全身 / 身材 / 姿态 / 性转","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-273", category: "portrait", subCategory: "sub-19", title: "体毛移除", image: BLACK, tags: ["人物-全身 / 身材 / 姿态 / 性转","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-274", category: "portrait", subCategory: "sub-19", title: "身材优化", image: WHITE, tags: ["人物-全身 / 身材 / 姿态 / 性转","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-275", category: "portrait", subCategory: "sub-19", title: "抹油勒肉", image: BLACK, tags: ["人物-全身 / 身材 / 姿态 / 性转","portrait"], prompt: '', params: "原始使用 0 次" },
  { id: "source-277", category: "outfit", subCategory: "sub-20", title: "衣服合身", image: WHITE, tags: ["服装-整体 / 版型 / 合身 / 褶皱","outfit"], prompt: '', params: "原始使用 4 次" },
  { id: "source-279", category: "outfit", subCategory: "sub-20", title: "跑裙子", image: BLACK, tags: ["服装-整体 / 版型 / 合身 / 褶皱","outfit"], prompt: '', params: "原始使用 1 次" },
  { id: "source-280", category: "outfit", subCategory: "sub-20", title: "绷紧衣服", image: WHITE, tags: ["服装-整体 / 版型 / 合身 / 褶皱","outfit"], prompt: '', params: "原始使用 0 次" },
  { id: "source-281", category: "outfit", subCategory: "sub-20", title: "明日香衣服优化", image: BLACK, tags: ["服装-整体 / 版型 / 合身 / 褶皱","outfit"], prompt: '', params: "原始使用 0 次" },
  { id: "source-282", category: "outfit", subCategory: "sub-20", title: "服装破损修复", image: WHITE, tags: ["服装-整体 / 版型 / 合身 / 褶皱","outfit"], prompt: '', params: "原始使用 0 次" },
  { id: "source-287", category: "outfit", subCategory: "sub-21", title: "中性灰黑丝", image: BLACK, tags: ["服装-丝袜 / 白丝 / 黑丝 / 网袜 / 打底","outfit"], prompt: '', params: "原始使用 0 次" },
  { id: "source-291", category: "outfit", subCategory: "sub-21", title: "纱衣去打底", image: WHITE, tags: ["服装-丝袜 / 白丝 / 黑丝 / 网袜 / 打底","outfit"], prompt: '', params: "原始使用 0 次" },
  { id: "source-292", category: "outfit", subCategory: "sub-21", title: "旗袍去打底", image: BLACK, tags: ["服装-丝袜 / 白丝 / 黑丝 / 网袜 / 打底","outfit"], prompt: '', params: "原始使用 0 次" },
  { id: "source-293", category: "outfit", subCategory: "sub-21", title: "旗袍开叉安全裤去除漏肉", image: WHITE, tags: ["服装-丝袜 / 白丝 / 黑丝 / 网袜 / 打底","outfit"], prompt: '', params: "原始使用 0 次" },
  { id: "source-294", category: "outfit", subCategory: "sub-21", title: "丝袜超写实", image: BLACK, tags: ["服装-丝袜 / 白丝 / 黑丝 / 网袜 / 打底","outfit"], prompt: '', params: "原始使用 1 次" },
  { id: "source-295", category: "outfit", subCategory: "sub-21", title: "丝袜优化+高亮", image: WHITE, tags: ["服装-丝袜 / 白丝 / 黑丝 / 网袜 / 打底","outfit"], prompt: '', params: "原始使用 1 次" },
  { id: "source-296", category: "outfit", subCategory: "sub-21", title: "白丝生成优化", image: BLACK, tags: ["服装-丝袜 / 白丝 / 黑丝 / 网袜 / 打底","outfit"], prompt: '', params: "原始使用 0 次" },
  { id: "source-297", category: "outfit", subCategory: "sub-21", title: "网袜渔网袜生成", image: WHITE, tags: ["服装-丝袜 / 白丝 / 黑丝 / 网袜 / 打底","outfit"], prompt: '', params: "原始使用 0 次" },
  { id: "source-298", category: "outfit", subCategory: "sub-21", title: "肉色裸感丝袜", image: BLACK, tags: ["服装-丝袜 / 白丝 / 黑丝 / 网袜 / 打底","outfit"], prompt: '', params: "原始使用 0 次" },
  { id: "source-299", category: "outfit", subCategory: "sub-21", title: "连体黑丝生成", image: WHITE, tags: ["服装-丝袜 / 白丝 / 黑丝 / 网袜 / 打底","outfit"], prompt: '', params: "原始使用 0 次" },
  { id: "source-300", category: "outfit", subCategory: "sub-21", title: "安全裤转丝袜", image: BLACK, tags: ["服装-丝袜 / 白丝 / 黑丝 / 网袜 / 打底","outfit"], prompt: '', params: "原始使用 0 次" },
  { id: "source-301", category: "outfit", subCategory: "sub-21", title: "去胸衣打底", image: WHITE, tags: ["服装-丝袜 / 白丝 / 黑丝 / 网袜 / 打底","outfit"], prompt: '', params: "原始使用 0 次" },
  { id: "source-302", category: "outfit", subCategory: "sub-21", title: "去打底裤", image: BLACK, tags: ["服装-丝袜 / 白丝 / 黑丝 / 网袜 / 打底","outfit"], prompt: '', params: "原始使用 0 次" },
  { id: "source-303", category: "outfit", subCategory: "sub-21", title: "旗袍去白色打底", image: WHITE, tags: ["服装-丝袜 / 白丝 / 黑丝 / 网袜 / 打底","outfit"], prompt: '', params: "原始使用 0 次" },
  { id: "source-304", category: "outfit", subCategory: "sub-21", title: "肩带内衣带移除", image: BLACK, tags: ["服装-丝袜 / 白丝 / 黑丝 / 网袜 / 打底","outfit"], prompt: '', params: "原始使用 0 次" },
  { id: "source-308", category: "outfit", subCategory: "sub-22", title: "配饰道具归位", image: WHITE, tags: ["配饰-饰品 / 头饰 / 小配件","outfit"], prompt: '', params: "原始使用 0 次" },
  { id: "source-309", category: "outfit", subCategory: "sub-22", title: "宝石镶嵌物优化", image: BLACK, tags: ["配饰-饰品 / 头饰 / 小配件","outfit"], prompt: '', params: "原始使用 0 次" },
  { id: "source-310", category: "material", subCategory: "sub-23", title: "布料超写实", image: WHITE, tags: ["材质-布料 / 针织 / 棉麻 / 丝绸","material","收藏"], prompt: '', params: "原始使用 37 次 / 收藏" },
  { id: "source-311", category: "material", subCategory: "sub-23", title: "增加棉麻纹理", image: BLACK, tags: ["材质-布料 / 针织 / 棉麻 / 丝绸","material"], prompt: '', params: "原始使用 11 次" },
  { id: "source-317", category: "material", subCategory: "sub-23", title: "增加衣服褶皱", image: WHITE, tags: ["材质-布料 / 针织 / 棉麻 / 丝绸","material"], prompt: '', params: "原始使用 3 次" },
  { id: "source-319", category: "material", subCategory: "sub-24", title: "皮革超写实", image: BLACK, tags: ["材质-皮革 / 尼龙 / 乳胶 / 装甲","material"], prompt: '', params: "原始使用 1 次" },
  { id: "source-320", category: "material", subCategory: "sub-24", title: "乳胶/胶手套", image: WHITE, tags: ["材质-皮革 / 尼龙 / 乳胶 / 装甲","material"], prompt: '', params: "原始使用 2 次" },
  { id: "source-321", category: "material", subCategory: "sub-24", title: "尼龙织带", image: BLACK, tags: ["材质-皮革 / 尼龙 / 乳胶 / 装甲","material"], prompt: '', params: "原始使用 37 次" },
  { id: "source-322", category: "material", subCategory: "sub-24", title: "皮革做旧磨损", image: WHITE, tags: ["材质-皮革 / 尼龙 / 乳胶 / 装甲","material"], prompt: '', params: "原始使用 1 次" },
  { id: "source-323", category: "material", subCategory: "sub-24", title: "布衣转机甲", image: BLACK, tags: ["材质-皮革 / 尼龙 / 乳胶 / 装甲","material"], prompt: '', params: "原始使用 0 次" },
  { id: "source-324", category: "material", subCategory: "sub-25", title: "物体质感（影视CG渲染 / 金属制品）", image: WHITE, tags: ["️ 材质-金属 / 木质 / 道具 / 通用物体","material"], prompt: '', params: "原始使用 7 次" },
  { id: "source-326", category: "material", subCategory: "sub-25", title: "金属超写实", image: BLACK, tags: ["️ 材质-金属 / 木质 / 道具 / 通用物体","material"], prompt: '', params: "原始使用 8 次" },
  { id: "source-327", category: "material", subCategory: "sub-25", title: "消除模型感", image: WHITE, tags: ["️ 材质-金属 / 木质 / 道具 / 通用物体","material"], prompt: '', params: "原始使用 1 次" },
  { id: "source-329", category: "material", subCategory: "sub-25", title: "修复拉链金属感", image: BLACK, tags: ["️ 材质-金属 / 木质 / 道具 / 通用物体","material"], prompt: '', params: "原始使用 1 次" },
  { id: "source-331", category: "material", subCategory: "sub-25", title: "道具金属化(可调参数)", image: WHITE, tags: ["️ 材质-金属 / 木质 / 道具 / 通用物体","material"], prompt: '', params: "原始使用 1 次" },
  { id: "source-332", category: "material", subCategory: "sub-25", title: "道具木质化(可调参数)", image: BLACK, tags: ["️ 材质-金属 / 木质 / 道具 / 通用物体","material"], prompt: '', params: "原始使用 2 次" },
  { id: "source-333", category: "material", subCategory: "sub-25", title: "道具做旧-锈蚀磨损(可调参数)", image: WHITE, tags: ["️ 材质-金属 / 木质 / 道具 / 通用物体","material"], prompt: '', params: "原始使用 0 次" },
  { id: "source-334", category: "material", subCategory: "sub-25", title: "道具做旧-战损破碎(可调参数)", image: BLACK, tags: ["️ 材质-金属 / 木质 / 道具 / 通用物体","material"], prompt: '', params: "原始使用 0 次" },
  { id: "source-335", category: "material", subCategory: "sub-25", title: "道具接缝消除", image: WHITE, tags: ["️ 材质-金属 / 木质 / 道具 / 通用物体","material"], prompt: '', params: "原始使用 0 次" },
  { id: "source-336", category: "material", subCategory: "sub-25", title: "道具清洁翻新", image: BLACK, tags: ["️ 材质-金属 / 木质 / 道具 / 通用物体","material"], prompt: '', params: "原始使用 0 次" },
  { id: "source-337", category: "material", subCategory: "sub-25", title: "道具表面精度提升", image: WHITE, tags: ["️ 材质-金属 / 木质 / 道具 / 通用物体","material"], prompt: '', params: "原始使用 0 次" },
  { id: "source-338", category: "material", subCategory: "sub-25", title: "道具套装材质统一", image: BLACK, tags: ["️ 材质-金属 / 木质 / 道具 / 通用物体","material"], prompt: '', params: "原始使用 0 次" },
  { id: "source-339", category: "material", subCategory: "sub-25", title: "通用物体材质升级", image: WHITE, tags: ["️ 材质-金属 / 木质 / 道具 / 通用物体","material"], prompt: '', params: "原始使用 0 次" },
  { id: "source-340", category: "material", subCategory: "sub-26", title: "武器发光", image: BLACK, tags: ["武器-枪械 / 刃口 / 战术装备","material"], prompt: '', params: "原始使用 0 次" },
  { id: "source-342", category: "material", subCategory: "sub-26", title: "刃口锋刃强化", image: WHITE, tags: ["武器-枪械 / 刃口 / 战术装备","material"], prompt: '', params: "原始使用 0 次" },
  { id: "source-345", category: "lighting", subCategory: "sub-27", title: "结构光微调", image: BLACK, tags: ["光影-布光 / 投影 / 反射 / AO","lighting"], prompt: '', params: "原始使用 3 次" },
  { id: "source-347", category: "lighting", subCategory: "sub-27", title: "替换光源（平台）", image: WHITE, tags: ["光影-布光 / 投影 / 反射 / AO","lighting"], prompt: '', params: "原始使用 1 次" },
  { id: "source-348", category: "lighting", subCategory: "sub-27", title: "打光微调", image: BLACK, tags: ["光影-布光 / 投影 / 反射 / AO","lighting"], prompt: '', params: "原始使用 0 次" },
  { id: "source-352", category: "lighting", subCategory: "sub-27", title: "保持原光色", image: WHITE, tags: ["光影-布光 / 投影 / 反射 / AO","lighting"], prompt: '', params: "原始使用 1 次" },
  { id: "source-355", category: "lighting", subCategory: "sub-27", title: "柔化阴影边缘", image: BLACK, tags: ["光影-布光 / 投影 / 反射 / AO","lighting"], prompt: '', params: "原始使用 1 次" },
  { id: "source-361", category: "lighting", subCategory: "sub-27", title: "提升暗部细节", image: WHITE, tags: ["光影-布光 / 投影 / 反射 / AO","lighting"], prompt: '', params: "原始使用 0 次" },
  { id: "source-362", category: "lighting", subCategory: "sub-27", title: "灯光微调", image: BLACK, tags: ["光影-布光 / 投影 / 反射 / AO","lighting"], prompt: '', params: "原始使用 0 次" },
  { id: "source-367", category: "lighting", subCategory: "sub-28", title: "暗调修肤色", image: WHITE, tags: ["氛围-调色 / 风格化 / 色温","lighting"], prompt: '', params: "原始使用 4 次" },
  { id: "source-369", category: "lighting", subCategory: "sub-28", title: "换氛围/色调", image: BLACK, tags: ["氛围-调色 / 风格化 / 色温","lighting"], prompt: '', params: "原始使用 2 次" },
  { id: "source-371", category: "lighting", subCategory: "sub-28", title: "降低饱和度", image: WHITE, tags: ["氛围-调色 / 风格化 / 色温","lighting"], prompt: '', params: "原始使用 0 次" },
  { id: "source-373", category: "lighting", subCategory: "sub-28", title: "色彩平衡校正", image: BLACK, tags: ["氛围-调色 / 风格化 / 色温","lighting"], prompt: '', params: "原始使用 1 次" },
  { id: "source-374", category: "lighting", subCategory: "sub-28", title: "赛博朋克风格化", image: WHITE, tags: ["氛围-调色 / 风格化 / 色温","lighting"], prompt: '', params: "原始使用 0 次" },
  { id: "source-375", category: "lighting", subCategory: "sub-28", title: "暗黑哥特风格化", image: BLACK, tags: ["氛围-调色 / 风格化 / 色温","lighting"], prompt: '', params: "原始使用 0 次" },
  { id: "source-376", category: "lighting", subCategory: "sub-28", title: "日系胶片清新", image: WHITE, tags: ["氛围-调色 / 风格化 / 色温","lighting"], prompt: '', params: "原始使用 0 次" },
  { id: "source-377", category: "lighting", subCategory: "sub-28", title: "电影感调色", image: BLACK, tags: ["氛围-调色 / 风格化 / 色温","lighting"], prompt: '', params: "原始使用 0 次" },
  { id: "source-378", category: "lighting", subCategory: "sub-28", title: "夜景霓虹氛围", image: WHITE, tags: ["氛围-调色 / 风格化 / 色温","lighting"], prompt: '', params: "原始使用 0 次" },
  { id: "source-394", category: "lighting", subCategory: "sub-29", title: "高清重绘", image: BLACK, tags: ["摄影-构图 / 镜头 / 景深 / 画质","lighting"], prompt: '', params: "原始使用 1 次" },
  { id: "source-397", category: "lighting", subCategory: "sub-29", title: "CG画质", image: WHITE, tags: ["摄影-构图 / 镜头 / 景深 / 画质","lighting"], prompt: '', params: "原始使用 4 次" },
  { id: "source-398", category: "lighting", subCategory: "sub-29", title: "影视画质", image: BLACK, tags: ["摄影-构图 / 镜头 / 景深 / 画质","lighting","收藏"], prompt: '', params: "原始使用 12 次 / 收藏" },
  { id: "source-403", category: "lighting", subCategory: "sub-29", title: "2/3构图", image: WHITE, tags: ["摄影-构图 / 镜头 / 景深 / 画质","lighting"], prompt: '', params: "原始使用 8 次" },
  { id: "source-404", category: "lighting", subCategory: "sub-29", title: "镜头质感", image: BLACK, tags: ["摄影-构图 / 镜头 / 景深 / 画质","lighting"], prompt: '', params: "原始使用 2 次" },
  { id: "source-409", category: "lighting", subCategory: "sub-29", title: "增加锐度", image: WHITE, tags: ["摄影-构图 / 镜头 / 景深 / 画质","lighting"], prompt: '', params: "原始使用 1 次" },
  { id: "source-412", category: "lighting", subCategory: "sub-29", title: "背景虚化景深", image: BLACK, tags: ["摄影-构图 / 镜头 / 景深 / 画质","lighting"], prompt: '', params: "原始使用 0 次" },
  { id: "source-413", category: "lighting", subCategory: "sub-29", title: "镜头光晕", image: WHITE, tags: ["摄影-构图 / 镜头 / 景深 / 画质","lighting"], prompt: '', params: "原始使用 0 次" },
  { id: "source-418", category: "base", subCategory: "sub-30", title: "清杂（去人/去灯架柔光箱/去杂物）", image: BLACK, tags: ["去杂物-擦除 / 修补 / 去水印 / 白棚","base"], prompt: '', params: "原始使用 2 次" },
  { id: "source-419", category: "base", subCategory: "sub-30", title: "外景", image: WHITE, tags: ["去杂物-擦除 / 修补 / 去水印 / 白棚","base"], prompt: '', params: "原始使用 1 次" },
  { id: "source-422", category: "base", subCategory: "sub-30", title: "移除灯架穿帮", image: BLACK, tags: ["去杂物-擦除 / 修补 / 去水印 / 白棚","base"], prompt: '', params: "原始使用 0 次" },
  { id: "source-423", category: "base", subCategory: "sub-30", title: "服装杂物移除", image: WHITE, tags: ["去杂物-擦除 / 修补 / 去水印 / 白棚","base"], prompt: '', params: "原始使用 0 次" },
  { id: "source-424", category: "base", subCategory: "sub-30", title: "地面杂物清理", image: BLACK, tags: ["去杂物-擦除 / 修补 / 去水印 / 白棚","base"], prompt: '', params: "原始使用 0 次" },
  { id: "source-425", category: "base", subCategory: "sub-30", title: "通用区域杂物擦除", image: WHITE, tags: ["去杂物-擦除 / 修补 / 去水印 / 白棚","base"], prompt: '', params: "原始使用 0 次" },
  { id: "source-426", category: "base", subCategory: "sub-30", title: "白棚处理", image: BLACK, tags: ["去杂物-擦除 / 修补 / 去水印 / 白棚","base"], prompt: '', params: "原始使用 0 次" },
  { id: "source-427", category: "base", subCategory: "sub-30", title: "实景棚处理", image: WHITE, tags: ["去杂物-擦除 / 修补 / 去水印 / 白棚","base"], prompt: '', params: "原始使用 0 次" },
  { id: "source-428", category: "base", subCategory: "sub-30", title: "场照除杂", image: BLACK, tags: ["去杂物-擦除 / 修补 / 去水印 / 白棚","base"], prompt: '', params: "原始使用 0 次" },
  { id: "source-429", category: "base", subCategory: "sub-30", title: "通用去水印文字", image: WHITE, tags: ["去杂物-擦除 / 修补 / 去水印 / 白棚","base"], prompt: '', params: "原始使用 0 次" },
  { id: "source-430", category: "base", subCategory: "sub-30", title: "场照清场-移除路人灯架器材", image: BLACK, tags: ["去杂物-擦除 / 修补 / 去水印 / 白棚","base"], prompt: '', params: "原始使用 0 次" },
  { id: "source-432", category: "base", subCategory: "sub-30", title: "场馆内只留主角", image: WHITE, tags: ["去杂物-擦除 / 修补 / 去水印 / 白棚","base"], prompt: '', params: "原始使用 0 次" },
  { id: "source-433", category: "scene", subCategory: "sub-31", title: "赛博朋克背景", image: BLACK, tags: ["️ 背景-抠图 / 换背景 / 场景替换","scene"], prompt: '', params: "原始使用 0 次" },
  { id: "source-434", category: "scene", subCategory: "sub-31", title: "场照去背景", image: WHITE, tags: ["️ 背景-抠图 / 换背景 / 场景替换","scene"], prompt: '', params: "原始使用 0 次" },
  { id: "source-437", category: "scene", subCategory: "sub-31", title: "新年场景", image: BLACK, tags: ["️ 背景-抠图 / 换背景 / 场景替换","scene"], prompt: '', params: "原始使用 0 次" },
  { id: "source-439", category: "scene", subCategory: "sub-31", title: "换背景", image: WHITE, tags: ["️ 背景-抠图 / 换背景 / 场景替换","scene"], prompt: '', params: "原始使用 0 次" },
  { id: "source-440", category: "scene", subCategory: "sub-31", title: "新春四合院场景", image: BLACK, tags: ["️ 背景-抠图 / 换背景 / 场景替换","scene"], prompt: '', params: "原始使用 0 次" },
  { id: "source-441", category: "scene", subCategory: "sub-31", title: "咖啡厅场景", image: WHITE, tags: ["️ 背景-抠图 / 换背景 / 场景替换","scene"], prompt: '', params: "原始使用 0 次" },
  { id: "source-442", category: "scene", subCategory: "sub-31", title: "中国风水墨意境", image: BLACK, tags: ["️ 背景-抠图 / 换背景 / 场景替换","scene"], prompt: '', params: "原始使用 0 次" },
  { id: "source-443", category: "scene", subCategory: "sub-31", title: "ai裹你脑版合成", image: WHITE, tags: ["️ 背景-抠图 / 换背景 / 场景替换","scene"], prompt: '', params: "原始使用 0 次" },
  { id: "source-458", category: "effect", subCategory: "sub-33", title: "全图特效光", image: BLACK, tags: ["特效-光效 / 粒子 / 元素 / 魔法","effect"], prompt: '', params: "原始使用 0 次" },
  { id: "source-461", category: "effect", subCategory: "sub-33", title: "九尾狐", image: WHITE, tags: ["特效-光效 / 粒子 / 元素 / 魔法","effect"], prompt: '', params: "原始使用 0 次" },
  { id: "source-462", category: "effect", subCategory: "sub-33", title: "魔法阵特效", image: BLACK, tags: ["特效-光效 / 粒子 / 元素 / 魔法","effect"], prompt: '', params: "原始使用 0 次" },
  { id: "source-463", category: "effect", subCategory: "sub-33", title: "火焰特效(环绕)", image: WHITE, tags: ["特效-光效 / 粒子 / 元素 / 魔法","effect"], prompt: '', params: "原始使用 0 次" },
  { id: "source-464", category: "effect", subCategory: "sub-33", title: "火焰特效(画笔引导)", image: BLACK, tags: ["特效-光效 / 粒子 / 元素 / 魔法","effect"], prompt: '', params: "原始使用 0 次" },
  { id: "source-465", category: "effect", subCategory: "sub-33", title: "冰霜特效", image: WHITE, tags: ["特效-光效 / 粒子 / 元素 / 魔法","effect"], prompt: '', params: "原始使用 0 次" },
  { id: "source-466", category: "effect", subCategory: "sub-33", title: "雷电特效(画笔引导)", image: BLACK, tags: ["特效-光效 / 粒子 / 元素 / 魔法","effect"], prompt: '', params: "原始使用 0 次" },
  { id: "source-467", category: "effect", subCategory: "sub-33", title: "风场特效(画笔引导)", image: WHITE, tags: ["特效-光效 / 粒子 / 元素 / 魔法","effect"], prompt: '', params: "原始使用 0 次" },
  { id: "source-468", category: "effect", subCategory: "sub-33", title: "暗影黑雾特效", image: BLACK, tags: ["特效-光效 / 粒子 / 元素 / 魔法","effect"], prompt: '', params: "原始使用 0 次" },
  { id: "source-469", category: "effect", subCategory: "sub-33", title: "通用元素特效(画笔引导)", image: WHITE, tags: ["特效-光效 / 粒子 / 元素 / 魔法","effect"], prompt: '', params: "原始使用 0 次" },
  { id: "source-470", category: "effect", subCategory: "sub-33", title: "樱花花瓣飘落", image: BLACK, tags: ["特效-光效 / 粒子 / 元素 / 魔法","effect"], prompt: '', params: "原始使用 0 次" },
  { id: "source-471", category: "effect", subCategory: "sub-33", title: "萤火虫光粒子", image: WHITE, tags: ["特效-光效 / 粒子 / 元素 / 魔法","effect"], prompt: '', params: "原始使用 0 次" },
  { id: "source-472", category: "effect", subCategory: "sub-33", title: "光翼生成", image: BLACK, tags: ["特效-光效 / 粒子 / 元素 / 魔法","effect"], prompt: '', params: "原始使用 0 次" },
  { id: "source-473", category: "effect", subCategory: "sub-33", title: "岩石大地特效", image: WHITE, tags: ["特效-光效 / 粒子 / 元素 / 魔法","effect"], prompt: '', params: "原始使用 0 次" },
  { id: "source-474", category: "effect", subCategory: "sub-33", title: "非人类特征优化", image: BLACK, tags: ["特效-光效 / 粒子 / 元素 / 魔法","effect"], prompt: '', params: "原始使用 0 次" },
  { id: "source-475", category: "effect", subCategory: "sub-33", title: "纹身花纹添加", image: WHITE, tags: ["特效-光效 / 粒子 / 元素 / 魔法","effect"], prompt: '', params: "原始使用 0 次" },
  { id: "source-482", category: "effect", subCategory: "sub-34", title: "浮空血液生成", image: BLACK, tags: ["特效-流体 / 湿身 / 雨水 / 粘液","effect"], prompt: '', params: "原始使用 0 次" },
  { id: "source-483", category: "effect", subCategory: "sub-34", title: "水流水体生成", image: WHITE, tags: ["特效-流体 / 湿身 / 雨水 / 粘液","effect"], prompt: '', params: "原始使用 0 次" },
  { id: "source-484", category: "effect", subCategory: "sub-34", title: "白色粘液生成", image: BLACK, tags: ["特效-流体 / 湿身 / 雨水 / 粘液","effect"], prompt: '', params: "原始使用 0 次" },
  { id: "source-485", category: "effect", subCategory: "sub-34", title: "白色粘液(画笔引导)", image: WHITE, tags: ["特效-流体 / 湿身 / 雨水 / 粘液","effect"], prompt: '', params: "原始使用 0 次" },
  { id: "source-486", category: "effect", subCategory: "sub-34", title: "湿身汗水效果", image: BLACK, tags: ["特效-流体 / 湿身 / 雨水 / 粘液","effect"], prompt: '', params: "原始使用 0 次" },
  { id: "source-487", category: "effect", subCategory: "sub-34", title: "毒雾腐蚀特效", image: WHITE, tags: ["特效-流体 / 湿身 / 雨水 / 粘液","effect"], prompt: '', params: "原始使用 0 次" },
  { id: "source-493", category: "effect", subCategory: "sub-35", title: "战斗伤疤生成", image: BLACK, tags: ["特效-战损 / 脏污 / 伤疤 / 老化","effect"], prompt: '', params: "原始使用 0 次" },
  { id: "source-494", category: "creative", subCategory: "sub-36", title: "动漫杂志封面", image: WHITE, tags: ["创意-植入 / 重构 / 动作设计 / 建模 / Fufu","creative"], prompt: '', params: "原始使用 0 次" },
  { id: "source-495", category: "creative", subCategory: "sub-36", title: "草图绘制（通用提示词）", image: BLACK, tags: ["创意-植入 / 重构 / 动作设计 / 建模 / Fufu","creative"], prompt: '', params: "原始使用 7 次" },
  { id: "source-501", category: "creative", subCategory: "sub-36", title: "凭空添加物体", image: WHITE, tags: ["创意-植入 / 重构 / 动作设计 / 建模 / Fufu","creative"], prompt: '', params: "原始使用 0 次" },
  { id: "source-503", category: "creative", subCategory: "sub-36", title: "截图出三视图", image: BLACK, tags: ["创意-植入 / 重构 / 动作设计 / 建模 / Fufu","creative"], prompt: '', params: "原始使用 1 次" },
  { id: "source-505", category: "creative", subCategory: "sub-36", title: "场照轮椅一键处理", image: WHITE, tags: ["创意-植入 / 重构 / 动作设计 / 建模 / Fufu","creative"], prompt: '', params: "原始使用 0 次" },
  { id: "source-506", category: "creative", subCategory: "sub-36", title: "2D转3D植入", image: BLACK, tags: ["创意-植入 / 重构 / 动作设计 / 建模 / Fufu","creative"], prompt: '', params: "原始使用 0 次" },
  { id: "source-507", category: "creative", subCategory: "sub-36", title: "凭空植入物体", image: WHITE, tags: ["创意-植入 / 重构 / 动作设计 / 建模 / Fufu","creative"], prompt: '', params: "原始使用 0 次" },
  { id: "source-508", category: "creative", subCategory: "sub-36", title: "动作设计(九宫格)", image: BLACK, tags: ["创意-植入 / 重构 / 动作设计 / 建模 / Fufu","creative"], prompt: '', params: "原始使用 0 次" },
  { id: "source-509", category: "creative", subCategory: "sub-36", title: "生成Fufu玩偶", image: WHITE, tags: ["创意-植入 / 重构 / 动作设计 / 建模 / Fufu","creative"], prompt: '', params: "原始使用 2 次" },
  { id: "source-511", category: "creative", subCategory: "sub-36", title: "红色长短箭头引导吹", image: BLACK, tags: ["创意-植入 / 重构 / 动作设计 / 建模 / Fufu","creative"], prompt: '', params: "原始使用 0 次" },
  ...personalCommonPlaceholders,
  ...semiCompositePrefabPlaceholders,
] as PromptLibraryItem[]).map((item) => ({ ...item, title: '' }))

export const getPromptCategory = (id: PromptLibraryCategoryId) => promptLibraryCategories.find((category) => category.id === id) ?? promptLibraryCategories[0]
export const getPromptSubcategory = (id: string) => promptLibrarySubcategories.find((category) => category.id === id)

